export const categories = [
  "All",
  "Food & Beverage",
  "Media",
  "Transport & Logistics",
  "Banking & Finance",
  "Lifestyle",
  "Co-incubation",
  "Healthcare",
  "Retail & Entertainment",
  "Telco",
  "Others",
  "Start-ups",
];

export const works = [
  {
    category: ["Banking & Finance"],
    title: "OCBC Pay Anyone",
    photo: "https://cdn.codigo.co/uploads/2021/04/PAO-0@2x.jpg",
    legends: ["app", "ui/ux"],
  },
  {
    category: ["Others"],
    title: "Ecolab",
    photo: "https://cdn.codigo.co/uploads/2021/04/ECO-0@2x.jpg",
    legends: ["app", "cms", "ui/ux"],
  },
  {
    category: ["Others", "Start-ups"],
    title: "KIWI Auto Market",
    legends: ["app", "cms", "ui/ux"],
    photo: "https://cdn.codigo.co/uploads/2021/04/KIWI-0@2x.jpg",
  },
  {
    category: ["Lifestyle"],
    title: "Furama Hotels",
    legends: ["app", "ui/ux"],
    photo: "https://cdn.codigo.co/uploads/2021/04/FURAMA-0@2x.jpg",
  },
  {
    category: ["Transport & Logistics"],
    title: "Woodlands Transport",
    photo: "https://cdn.codigo.co/uploads/2021/04/WTS-0@2x.jpg",
    legends: ["app", "web", "cms", "ui/ux"],
  },
  {
    category: ["Lifestyle", "Retail & Entertainment", "Start-ups"],
    title: "Ready To Travel (SATS)",
    photo: "https://cdn.codigo.co/uploads/2021/04/RTT-0@2x.jpg",
    legends: ["app", "web", "cms", "ui/ux"],
  },
  {
    category: ["Lifestyle"],
    title: "Yoga Movement",
    photo: "https://cdn.codigo.co/uploads/2021/04/YM-0@2x-1.jpg",
    legends: ["app", "web", "cms", "ui/ux"],
  },
  {
    category: ["Retail & Entertainment"],
    title: "Don Don Donki",
    photo: "https://cdn.codigo.co/uploads/2021/04/DONKI-0@2x.jpg",
    legends: ["app", "cms", "ui/ux"],
  },
  {
    category: ["Transport & Logistics"],
    title: "TAB Ride Hailing",
    photo: "https://cdn.codigo.co/uploads/2021/04/TAP-0@2x.jpg",
    legends: ["app"],
  },
  {
    category: ["Retail & Entertainment"],
    title: "Isetan",
    photo: "https://cdn.codigo.co/uploads/2021/04/ISETAN-0@2x.jpg",
    legends: ["app", "cms", "ui/ux"],
  },
  {
    category: ["Others"],
    title: "FWD Insurance",
    photo: "https://cdn.codigo.co/uploads/2021/04/HBO-0@2x-2.jpg",
    legends: ["app", "cms", "ui/ux"],
  },
  {
    category: ["Telco"],
    title: "MyRepublic Mobile",
    photo: "https://cdn.codigo.co/uploads/2018/12/MYR.jpg",
    legends: ["app", "ui/ux"],
  },
  {
    category: ["Transport & Logistics"],
    title: "ComfortDelGro",
    photo: "https://cdn.codigo.co/uploads/2018/08/CDG-2-1.jpg",
    legends: ["app"],
  },
  {
    category: ["Retail & Entertainment"],
    title: "7Rewards",
    photo: "https://cdn.codigo.co/uploads/2018/04/711.jpg",
    legends: ["app", "web", "cms"],
  },
  {
    category: ["Retail & Entertainment"],
    title: "FairPrice Online",
    photo: "https://cdn.codigo.co/uploads/2018/08/FPOL.jpg",
    legends: ["ui/ux"],
  },
  {
    category: ["Retail & Entertainment"],
    title: "Charles & Keith / Pedro",
    photo: "https://cdn.codigo.co/uploads/2018/12/ck.jpg",
    legends: ["app"],
  },
  {
    category: ["Retail & Entertainment"],
    title: "Justice League",
    photo:
      "https://cdn.codigo.co/uploads/2018/11/thumbnail-justice_league@2x.jpg",
    legends: ["app"],
  },
  {
    category: ["Healthcare"],
    title: "Fullerton Health",
    photo:
      "https://cdn.codigo.co/uploads/2018/11/fullerton-health-thumbnail@2x.jpg",
    legends: ["app"],
  },
  {
    category: ["Lifestyle"],
    title: "Sky Premium",
    photo: "https://cdn.codigo.co/uploads/2018/11/skypremium-thumbnail@2x.jpg",
    legends: ["app", "web"],
  },
  {
    category: ["Lifestyle"],
    title: "T Singapore",
    photo: "https://cdn.codigo.co/uploads/2018/12/TSingapore-thumbnail@2x.jpg",
    legends: ["web", "cms"],
  },
  {
    category: ["Transport & Logistics"],
    title: "SingPost",
    photo: "https://cdn.codigo.co/uploads/2018/12/singpost-thumbnail@2x.jpg",
    legends: ["app", "ui/ux"],
  },
  {
    category: ["Co-incubation", "Start-ups", "Food & Beverage"],
    title: "Dine Inn",
    photo: "https://cdn.codigo.co/uploads/2018/12/dineinn.jpg",
    legends: ["app", "web", "cms"],
  },
  {
    category: ["Transport & Logistics"],
    title: "Siemens Engineering",
    photo: "https://cdn.codigo.co/uploads/2018/11/siemens.jpg",
    legends: ["app", "web", "cms"],
  },
  {
    category: ["Transport & Logistics", "Co-incubation", "Start-ups"],
    title: "FastFast Delivery",
    photo: "https://cdn.codigo.co/uploads/2018/12/FF-1.jpg",
    legends: ["app", "web", "cms"],
  },
  {
    category: [],
    title: "Singapore Grand Prix",
    photo: "https://cdn.codigo.co/uploads/2018/12/f1.jpg",
    legends: ["app", "web", "cms"],
  },
  {
    category: ["Food & Beverage"],
    title: "McDonald's",
    photo: "https://cdn.codigo.co/uploads/2018/12/mc-cafe-thumbnail@2x.jpg",
    legends: ["app"],
  },
];
